# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-proteomicslfq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # bioconda
  - bioconda::openms-thirdparty=2.5.0
  - bioconda::bioconductor-msstats # will include R
  #TODO check if thirdparties are in path and are found by the openms adapters
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2

