# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-proteomicslfq-1.0dev
channels:
  - openms
  - conda-forge
  - bioconda
dependencies:
  # TODO fix versions for release (and also for develop, as soon as we have official nightly conda packages, with e.g. a date as version)
  - openms::openms=2.6.0pre # nightly version of 2.6
  - bioconda::thermorawfileparser=1.2.3
  - bioconda::msgf_plus=2020.08.05
  - bioconda::comet-ms=2019015
  - bioconda::luciphor2=2020_04_03
  - bioconda::percolator=3.5
  - bioconda::bioconductor-msstats=3.20.1 # will include R
  - bioconda::sdrf-pipelines=0.0.9 # for SDRF conversion
  - conda-forge::r-ptxqc=1.0.5 # for QC reports
  - conda-forge::xorg-libxt=1.2.0 # until this R fix is merged: https://github.com/conda-forge/r-base-feedstock/pull/128
  - conda-forge::fonts-conda-ecosystem=1 # for the fonts in QC reports
  - conda-forge::openjdk=8.* # pin java to 8 for MSGF (otherwise it somehow chooses 11)
  - conda-forge::python=3.8.1
  - conda-forge::markdown=3.2.1
  - conda-forge::pymdown-extensions=7.1
  - conda-forge::pygments=2.5.2

